### ISSUE TITLE
search/streams keeps returning 0 result

### ISSUE THREAD

**Issue by ebongso** [justintv/Twitch-API#495]
Hello,
I haven't been able to get any results from the search/streams endpoint since yesterday (2/2). It had been working fine up until Feb 1st. I tried `https://api.twitch.tv/kraken/search/streams?q=starcraft` with and without client_id. They both return 0 result. 
```
{
  "_total":0,
  "_links":
  {
    "self":"https://api.twitch.tv/kraken/search/streams?limit=10&offset=0&q=starcraft",
    "next":"https://api.twitch.tv/kraken/search/streams?limit=10&offset=10&q=starcraft"
  },
  "streams":[]}
```

Any help is appreciated. Thank you.

**Comment by Fugiman** [comment]
This should be fixed now, thank you for your report!

**Comment by arnoldsandoval** [comment]
Sorry to comment on a closed issue, but this still appears to be happening for me. Should I open a new issue?
