### ISSUE TITLE
Chrome is canceling request to Auth Page

### ISSUE THREAD

**Issue by nfMalde** [justintv/Twitch-API#530]
Hi
Im testing arround at the moment with the Twitch API.

Im Testing on: .NET MVC 5, Localhost.
I tryed to redirect the user to 
https://api.twitch.tv/kraken/oauth2/authorize?response_type=code&client_id=....&redirect_uri=http://localhost:63477/ExternalConnections/Twitch/Authorize&scope=user_read+channel_read&state=...

Somehow the request is getting canceled by chrome. Firefox is working. Is there something wrong in my call or why is only chrome canceling the request?

Here is a screenshot from the network tab:
![twitchrequest](https://cloud.githubusercontent.com/assets/5366984/14228078/98516024-f90b-11e5-8576-de99efcdae4b.png)

**Comment by 3ventic** [comment]
Not sure if related, but you should URL encode the redirect_uri value.

**Comment by nfMalde** [comment]
Done. I also removed all parameters except client_id and response_type. Request is still cancelled.

**Comment by DallasNChains** [comment]
If this isn't resolved, I would re-ask in the [Twitch Developer Forums](https://discuss.dev.twitch.tv).
